apiVersion: v1
kind: Service
metadata:
  name: devops-05-pipeline-aws
  labels:
    app: devops-05-pipeline-aws
    team: frontend  
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: devops-05-pipeline-aws

